l:
  name: LIJX_DEMO
  version: 1.0.0
server:
  port: 8999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #  type-enums-package:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  # 扫描bean下面的 BE
  type-aliases-package: com.lijx.**.bean